version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: account
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: account
      PORT: ":8080"
volumes:
  db-data: